DROP TABLE IF EXISTS kasa;
  
CREATE TABLE kasa (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  parduotuvesPavadinimas VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS veiksmas;
  
CREATE TABLE veiksmas (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  inOut INT NOT NULL,
  data VARCHAR (50) NOT NULL,
  kasosId INT NOT NULL,
  suma FLOAT NOT NULL
);

DROP TABLE IF EXISTS veiksmai;
DROP TABLE IF EXISTS zmogus;
DROP TABLE IF EXISTS preke;